name: Truba

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          cd scripts/build-domains
          chmod +x ../../bin/build-domains
          ../../bin/build-domains

      - name: Создать / обновить GitHub Release
        uses: softprops/action-gh-release@v2

        with:
          tag_name: ${{ github.event.pull_request.head.ref }}
          name: ${{ github.event.pull_request.head.ref }}
          fail_on_unmatched_files: false

          body: |
            ${{ github.event.pull_request.body }}

            SHA:: ${{ github.sha }}
            TAG: ${{ github.event.pull_request.head.ref }}

          files: |
            ./scripts/build-domains/dist/*.dat
